module.exports = {
    characters: [
        { "id": "char-cassie-lang", "name": "Cassie Lang", "aliases": ["Stature"] },
        { "id": "char-janet-van-dyne", "name": "Janet Van Dyne", "aliases": ["Original Wasp"] },
        { "id": "char-modok", "name": "M.O.D.O.K.", "aliases": ["Darren Cross"] },
        { "id": "char-high-evolutionary", "name": "High Evolutionary", "aliases": [] },
        { "id": "char-adam-warlock", "name": "Adam Warlock", "aliases": [] },
        { "id": "char-dar-benn", "name": "Dar-Benn", "aliases": [] },
        { "id": "char-talos", "name": "Talos", "aliases": [] },
        { "id": "char-gravik", "name": "Gravik", "aliases": [] },
        { "id": "char-giah", "name": "G'iah", "aliases": [] },
        { "id": "char-maria-hill", "name": "Maria Hill", "aliases": [] },
        { "id": "char-shang-chi", "name": "Shang-Chi", "aliases": [] },
        { "id": "char-xu-wenwu", "name": "Xu Wenwu", "aliases": ["The Mandarin"] },
        { "id": "char-katy", "name": "Katy Chen", "aliases": [] },
        { "id": "char-xu-xialing", "name": "Xu Xialing", "aliases": [] },
        { "id": "char-ying-nan", "name": "Ying Nan", "aliases": [] },
        { "id": "char-trevor-slattery", "name": "Trevor Slattery", "aliases": [] },
        { "id": "char-abomination", "name": "Emil Blonsky", "aliases": ["Abomination"] },
        { "id": "char-wong", "name": "Wong", "aliases": ["Sorcerer Supreme"] },
        { "id": "char-sersi", "name": "Sersi", "aliases": [] },
        { "id": "char-ikaris", "name": "Ikaris", "aliases": [] },
        { "id": "char-kingo", "name": "Kingo", "aliases": [] },
        { "id": "char-sprite", "name": "Sprite", "aliases": [] },
        { "id": "char-phastos", "name": "Phastos", "aliases": [] },
        { "id": "char-makkari", "name": "Makkari", "aliases": [] },
        { "id": "char-druig", "name": "Druig", "aliases": [] },
        { "id": "char-gilgamesh", "name": "Gilgamesh", "aliases": [] },
        { "id": "char-ajak", "name": "Ajak", "aliases": [] },
        { "id": "char-thena", "name": "Thena", "aliases": [] },
        { "id": "char-dane-whitman", "name": "Dane Whitman", "aliases": ["Black Knight"] },
        { "id": "char-arishem", "name": "Arishem", "aliases": ["The Judge"] },
        { "id": "char-mj", "name": "Michelle Jones-Watson", "aliases": ["MJ"] },
        { "id": "char-ned-leeds", "name": "Ned Leeds", "aliases": [] },
        { "id": "char-america-chavez", "name": "America Chavez", "aliases": [] },
        { "id": "char-christine-palmer", "name": "Christine Palmer", "aliases": [] },
        { "id": "char-jane-foster", "name": "Jane Foster", "aliases": ["Mighty Thor"] },
        { "id": "char-valkyrie", "name": "Valkyrie", "aliases": ["King of New Asgard"] },
        { "id": "char-gorr", "name": "Gorr", "aliases": ["The God Butcher"] },
        { "id": "char-korg", "name": "Korg", "aliases": [] },
        { "id": "char-zeus", "name": "Zeus", "aliases": [] },
        { "id": "char-shuri", "name": "Shuri", "aliases": ["Black Panther"] },
        { "id": "char-namor", "name": "Namor", "aliases": ["Kukulkan"] },
        { "id": "char-ramonda", "name": "Ramonda", "aliases": ["Queen Mother"] },
        { "id": "char-okoye", "name": "Okoye", "aliases": [] },
        { "id": "char-riri-williams", "name": "Riri Williams", "aliases": ["Ironheart"] },
        { "id": "char-mbaku", "name": "M'Baku", "aliases": [] },
        { "id": "char-nakia", "name": "Nakia", "aliases": [] },
        { "id": "char-everett-ross", "name": "Everett Ross", "aliases": [] },
        { "id": "char-charles-xavier", "name": "Charles Xavier", "aliases": ["Professor X"] },
        { "id": "char-reed-richards", "name": "Reed Richards", "aliases": ["Mister Fantastic"] },
        { "id": "char-peggy-carter", "name": "Peggy Carter", "aliases": ["Captain Carter"] },
        { "id": "char-norman-osborn", "name": "Norman Osborn", "aliases": ["Green Goblin"] },
        { "id": "char-otto-octavius", "name": "Otto Octavius", "aliases": ["Doctor Octopus"] }
    ],
    variants: [
        { "id": "variant-kang-conqueror", "name": "Kang the Conqueror", "baseCharacter": "char-he-who-remains" },
        { "id": "variant-peter-parker-webb", "name": "Peter Parker (Webb)", "baseCharacter": "char-peter-parker" },
        { "id": "variant-peter-parker-raimi", "name": "Peter Parker (Raimi)", "baseCharacter": "char-peter-parker" },
        { "id": "variant-norman-osborn", "name": "Norman Osborn", "baseCharacter": "char-norman-osborn" }, // Needs base? Let's just create char-norman-osborn for base.
        { "id": "variant-otto-octavius", "name": "Otto Octavius", "baseCharacter": "char-otto-octavius" },
        { "id": "variant-illuminati-prof-x", "name": "Professor X (838)", "baseCharacter": "char-charles-xavier" },
        { "id": "variant-illuminati-mr-fantastic", "name": "Mister Fantastic (838)", "baseCharacter": "char-reed-richards" },
        { "id": "variant-illuminati-captain-carter", "name": "Captain Carter (838)", "baseCharacter": "char-peggy-carter" },
        { "id": "variant-gamora-endgame", "name": "Gamora (2014 Variant)", "baseCharacter": "char-gamora" }
    ],
    organizations: [
        { "id": "org-red-room", "name": "Red Room", "founded": "Unknown" },
        { "id": "org-ten-rings", "name": "Ten Rings", "founded": "Ancient" },
        { "id": "org-eternals", "name": "Eternals", "founded": "Ancient" },
        { "id": "org-deviants", "name": "Deviants", "founded": "Ancient" },
        { "id": "org-celestials", "name": "Celestials", "founded": "Dawn of Time" },
        { "id": "org-illuminati", "name": "Illuminati", "founded": "Unknown" },
        { "id": "org-talokan", "name": "Talokan", "founded": "16th Century" },
        { "id": "org-flag-smashers", "name": "Flag Smashers", "founded": "2023" },
        { "id": "org-council-of-kangs", "name": "Council of Kangs", "founded": "Unknown" },
        { "id": "org-sovereign", "name": "Sovereign", "founded": "Unknown" },
        { "id": "org-saber", "name": "S.A.B.E.R.", "founded": "Unknown" },
        { "id": "org-kree-empire", "name": "Kree Empire", "founded": "Ancient" },
        { "id": "org-skrulls", "name": "Skrull Resistance", "founded": "Unknown" }
    ],
    locations: [
        { "id": "loc-red-room-base", "name": "Red Room Base", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-ta-lo", "name": "Ta Lo", "planet": "Ta Lo", "realm": "Multiverse" },
        { "id": "loc-macau", "name": "Macau", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-domo", "name": "The Domo", "planet": "Space", "realm": "Space" },
        { "id": "loc-new-york-sanctum", "name": "New York Sanctum", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-statue-of-liberty", "name": "Statue of Liberty", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-kamar-taj", "name": "Kamar-Taj", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-mount-wundagore", "name": "Mount Wundagore", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-new-asgard", "name": "New Asgard", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-omnipotence-city", "name": "Omnipotence City", "planet": "Unknown", "realm": "Gods" },
        { "id": "loc-eternity-realm", "name": "Realm of Eternity", "planet": "Unknown", "realm": "Cosmic" },
        { "id": "loc-talokan", "name": "Talokan", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-westview", "name": "Westview", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-london", "name": "London", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-cairo", "name": "Cairo", "planet": "Earth", "realm": "Midgard" },
        { "id": "loc-duat", "name": "Duat", "planet": "Duat", "realm": "Afterlife" },
        { "id": "loc-counter-earth", "name": "Counter-Earth", "planet": "Counter-Earth", "realm": "Space" },
        { "id": "loc-hala", "name": "Hala", "planet": "Hala", "realm": "Kree" },
        { "id": "loc-tarnax", "name": "Tarnax", "planet": "Tarnax", "realm": "Skrull" }
    ],
    artifacts: [
        { "id": "art-ten-rings", "name": "Ten Rings", "abilities": ["Energy Manipulation", "Immortality"] },
        { "id": "art-darkhold", "name": "Darkhold", "abilities": ["Dark Magic", "Dreamwalking"] },
        { "id": "art-book-of-vishanti", "name": "Book of Vishanti", "abilities": ["White Magic"] },
        { "id": "art-stormbreaker", "name": "Stormbreaker", "abilities": ["Bifrost Summoning", "Energy Projection"] },
        { "id": "art-necrosword", "name": "All-Black the Necrosword", "abilities": ["God-Killing"] },
        { "id": "art-kamala-bangle", "name": "Kamala's Bangle", "abilities": ["Hard Light Projection"] },
        { "id": "art-quantum-bands", "name": "Quantum Bands", "abilities": ["Space-Time Manipulation"] }
    ],
    technologies: [
        { "id": "tech-vibranium", "name": "Vibranium Tech", "purpose": "Defense and Offense" },
        { "id": "tech-ironheart-armor", "name": "Ironheart Armor", "purpose": "Combat / Flight" }
    ],
    events: [
        { "id": "event-the-emergence", "name": "The Emergence", "date": "2023", "location": "loc-earth" },
        { "id": "event-runes-of-kauf-kaul", "name": "Runes of Kof-Kol", "date": "2024", "location": "loc-new-york-sanctum" },
        { "id": "event-assault-on-kamar-taj", "name": "Assault on Kamar-Taj", "date": "2024", "location": "loc-kamar-taj" },
        { "id": "event-the-hex", "name": "The Westview Hex", "date": "2023", "location": "loc-westview" }
    ]
};
